### ISSUE TITLE
Default branch name update

### ISSUE THREAD

**Issue by 130s** [plusone-robotics/openni2_camera#6]
Because `indigo-devel` branch on this forked repo diverged from the one at the origin's, there are 2 `indigo-devel` branches with different content now and thus they can't co-exist on a local repo. This prevents me from cherry-picking the changes that are made on either repo.

I suggest to change `indigo-devel` on this fork to something unique as e.g. `por_indigo`.

**Comment by geoffreychiou** [comment]
I believe in some of our other github forks ([rapp_platform](https://github.com/plusone-robotics/rapp-platform), [rosparam_handler](https://github.com/plusone-robotics/rosparam_handler/tree/plusone/master)) we've been using the `plusone/branch-name` nomenclature.

**Comment by 130s** [comment]
I see. Then, my personal (but I think global as well?) practice for branch naming is to avoid slash to prevent name space collision like [this](https://stackoverflow.com/questions/2527355/using-the-slash-character-in-git-branch-name?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by geoffreychiou** [comment]
Good point, didn't know about that. We should definitely avoid using `plusone/branch`  from now on then.

**Comment by 130s** [comment]
Created [por_indigo](https://github.com/plusone-robotics/openni2_camera/tree/por_indigo) branch and set it as the default on this forked repo.

So I suggest 2 practices:
- No slash in branch name. Late in the branch name is fine (e.g. xxxxxxxxxxxxxxxx/indigo) as there's less chance for the namespace to collide). 
- If the "master" branch on the forked repo diverges from the one on the origin, rename the branch.
